### ISSUE TITLE
[Bug]: Candy Instantly Disappears Upon Opening Bag

### ISSUE THREAD

**Issue by HockeyZman2000** [samedifferent/TrickOrTreat#10]
### Mod Version

1.0.2

### Mod Loader

Forge

### Mod Loader Version

36.2.5

### What happened?

*Mod Incompatibility* Tested by itself and it works normally.

Right clicking a candy bag shows the corresponding candy for a brief millisecond before disappearing. Specifically the only candy bag that works how it normally should is the zombie candy bag which I find to be very strange. If I had to guess, I would say the problem is stemming from the series of "null" errors in the client log when trying to use the bags on the server. Not sure what mod might be causing the issue.

### latest.log

Server Log:
[latest.log](https://github.com/samedifferent/TrickOrTreat/files/7444665/latest.log)

Client Log:
[latest.log](https://github.com/samedifferent/TrickOrTreat/files/7444671/latest.log)

**Comment by samedifferent** [comment]
This is a known issue and I fixed it in the 1.17.1 version. I will put out a fix for the 1.16.5 version as well later today probably. The issue is the fact that the player has a full Hotbar when opening the bag. As a temporary fix, you can just make sure your hotbar has an empty slot before opening the bag.

**Comment by HockeyZman2000** [comment]
Okay sounds good! Thanks for the quick reply.

**Comment by viiizee** [comment]
I've noticed that this issue is persisting in the newest version. For example, a singular goodie bag on a full hotbar is not able to recognize that the slot the bag once occupied is now empty. Is there no way to make it so if the bag is opened and there is no space that the item just drops from the player?

**Comment by samedifferent** [comment]
Update has been released to fix it. Version 1.16.5-1.0.3
